Replace usages of findProperty
google/ksp pull request #2034
Opened 2024-08-18 15:16 UTC by ansman

`findProperty` is not compatible with project isolation. The new `providers.gradleProperty` is however.

This partially fixes #1752

2024-08-20 23:20 UTC, ting-yuan approved these changes

2024-08-21 08:54 UTC, merged

2024-09-06 20:16 UTC, ZacSweers commented
I'd like to request that this be either reverted or expose another way to enable/disable KSP2 per-project or per-task. With this change, it can only be enabled/disabled globally because `ProviderFactory.gradleProperty()` only reads the root project's gradle properties.

2024-09-06 20:32 UTC, ansman commented
@ZacSweers Fix in https://github.com/google/ksp/pull/2089

2025-01-06 09:03 UTC, Monday1908 requested changes
API29